### ISSUE TITLE
Toolbox heater not taking temperature settings

### ISSUE THREAD

**Issue by wifijt** [Spettacolo83/homeassistant-vevor-heater#1]
I have the newest version of the Vevor 8KW  toolbox heater with bluetooth. 

https://www.vevor.com/diesel-heater-c_10321/vevor-diesel-air-heater-12v-24v-8kw-bluetooth-app-remote-control-for-vehicles-p_010692097003

I am running an ESPHome BLE proxy and the Vevor controller is set to F

All of the functions work (setting mode, setting gear level, status information etc) - however when I am in temperature mode I cannot set the target temperature slider - it says it's set to 36c - I can change the temp in HA, but it reverts back to 36c. Same on the climate control - though that's showing 97F

<img width="870" height="669" alt="Image" src="https://github.com/user-attachments/assets/3b5b4136-0434-45f7-a32c-c257aaa92993" />

In the error logs I get this message:

2025-12-04 23:10:26.688 ERROR (MainThread) [custom_components.vevor_heater.coordinator] Error sending command: Peripheral 3C:AB:72:7A:10:E0 changed connection status while waiting for BluetoothGATTWriteResponse, BluetoothGATTErrorResponse: Insufficient authorization (8)

**Comment by wifijt** [comment]
Upgraded to the 1.0.10 - restarted HA - no change still shows set temp as 36 C (97F) - unit is set to 55F - when I make a change it doesn't take and reverts back to max temp

2025-12-07 15:52:16.239 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📤 Sending command: aa550c220100002f (cmd=1, arg=0)
2025-12-07 15:52:16.609 INFO (MainThread) [custom_components.vevor_heater.climate] Setting target temperature to 15°C
2025-12-07 15:52:16.609 INFO (MainThread) [custom_components.vevor_heater.coordinator] Setting target temperature to 15°C
2025-12-07 15:52:16.609 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📤 Sending command: aa550c22040f0041 (cmd=4, arg=15)
2025-12-07 15:52:16.771 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📩 Received BLE data (48 bytes): da077272776f7264724f7273f56f2b6470617376166e386470617372766e8d65700f7373136f726470617373776f7264
2025-12-07 15:52:16.771 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Parsed AA66 encrypted: {'running_state': 1, 'error_code': 0, 'running_step': 0, 'altitude': 0.0, 'running_mode': 2, 'set_level': 1, 'set_temp': 36, 'supply_voltage': 13.0, 'case_temperature': 89, 'cab_temperature': 11.0, 'connected': True, 'hourly_fuel_consumption': 0.0, 'daily_fuel_consumed': 1.53, 'total_fuel_consumed': 15.22, 'daily_fuel_history': {'2025-12-03': 2.26, '2025-12-04': 3.53, '2025-12-05': 4.06, '2025-12-06': 3.83}}
2025-12-07 15:52:16.812 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Received response after 0.1s
2025-12-07 15:52:16.847 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Received response after 0.5s
2025-12-07 15:52:16.847 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Finished fetching vevor_heater data in 0.608 seconds (success: True)
2025-12-07 15:52:16.885 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📩 Received BLE data (48 bytes): da077772776f7264724f7273f56f2b6470617376166e386470617372766e8d65700f7373136f726470617373776f7264
2025-12-07 15:52:16.885 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Parsed AA66 encrypted: {'running_state': 1, 'error_code': 0, 'running_step': 0, 'altitude': 0.0, 'running_mode': 2, 'set_level': 1, 'set_temp': 36, 'supply_voltage': 13.0, 'case_temperature': 89, 'cab_temperature': 11.0, 'connected': True, 'hourly_fuel_consumption': 0.0, 'daily_fuel_consumed': 1.53, 'total_fuel_consumed': 15.22, 'daily_fuel_history': {'2025-12-03': 2.26, '2025-12-04': 3.53, '2025-12-05': 4.06, '2025-12-06': 3.83}}

**Comment by Spettacolo83** [comment]
Hi @wifijt,

I've analyzed your logs and found the issue! Your heater uses **AA66 encrypted protocol** (48 bytes), but I was sending commands in **AA55 unencrypted format**. The heater was receiving the command but ignoring it because the format was wrong.

I've created a beta release that should fix this: **v1.0.11-beta.1**

### What's changed:
- Commands now automatically detect your heater's protocol (AA66 encrypted)
- Commands are sent encrypted using the same XOR encryption as responses
- Added extensive debug logging to track exactly what's happening

### To test:

1. **Download the beta:**
   https://github.com/Spettacolo83/homeassistant-vevor-heater/releases/tag/v1.0.11-beta.1

2. **Replace your integration files:**
   - Download and extract the release
   - Replace `/config/custom_components/vevor_heater/` with the new files
   
3. **Restart Home Assistant completely**

4. **Try setting the temperature** (e.g., 20°C)

5. **Check the logs** (Settings → System → Logs → search "vevor")

### What to look for in logs:

```
🔍 Detected protocol: AA66 encrypted (mode=4)
📋 Protocol mode changed: 0 → 4 (commands will now use AA66 encrypted format)
🔧 Building command packet: protocol_mode=4, cmd=4, arg=20
📤 Sending command: [encrypted hex] (cmd=4, arg=20, protocol=4, len=48)
🌡️ SET TEMPERATURE RESULT: requested=20°C, heater_reports=??°C, ✅ SUCCESS or ❌ FAILED
```

**Please share the relevant log entries** so I can verify the fix is working correctly. If it still fails, the logs will help me understand what's happening.

Thanks for your patience! 🙏

**Comment by wifijt** [comment]
Hmm - no luck - after the reboot the heater stopped responding to the BLE requests - I deleted the integration, restarted HA and then re-added it. Still no luck but here are the full logs from discovery to the failed attempt to query

EDIT: Actually it looks like it did query successfully once in the process

2025-12-07 16:39:20.974 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Scanning for Vevor heaters, found 16 BLE devices
2025-12-07 16:39:20.975 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device 4B:98:F1:8B:D2:1C (4B:98:F1:8B:D2:1C): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.975 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device 3C:AB:72:7A:10:E0 (BYD-3CAB727A10E0): service_uuid=True, name_match=False, manufacturer=False
2025-12-07 16:39:20.975 INFO (MainThread) [custom_components.vevor_heater.config_flow] Found potential Vevor heater: 3C:AB:72:7A:10:E0 (BYD-3CAB727A10E0)
2025-12-07 16:39:20.975 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device 5E:64:F9:87:B3:44 (5E:64:F9:87:B3:44): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.975 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device F6:EE:B0:BA:67:3F (F6:EE:B0:BA:67:3F): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.975 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device F7:C1:15:49:D5:96 (F7:C1:15:49:D5:96): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.975 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device 74:2F:87:71:FE:AB (LE-Sparkle Storm): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.975 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device 60:B7:6E:89:02:0F (setup02140): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.975 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device DB:F4:FE:CD:68:60 (DB:F4:FE:CD:68:60): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.975 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device FB:DB:6D:FD:E1:79 (FB:DB:6D:FD:E1:79): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.976 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device E0:9D:13:90:82:A3 (E0:9D:13:90:82:A3): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.976 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device C1:FC:C0:FB:0E:A2 (NF7TB): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.976 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device A8:51:AB:BE:F7:EB (A8:51:AB:BE:F7:EB): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.976 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device 42:68:C6:62:E6:F1 (42:68:C6:62:E6:F1): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.976 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device EA:4B:D0:92:31:AB (EA:4B:D0:92:31:AB): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.976 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device F4:DA:64:C6:55:DD (F4:DA:64:C6:55:DD): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:20.976 DEBUG (MainThread) [custom_components.vevor_heater.config_flow] Device F2:F7:4D:BA:85:FE (NF7NE): service_uuid=False, name_match=False, manufacturer=False
2025-12-07 16:39:23.482 DEBUG (MainThread) [custom_components.vevor_heater] Setting up Vevor Heater with address: 3C:AB:72:7A:10:E0
2025-12-07 16:39:23.500 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Loaded fuel data: total=15.22L, daily=1.53L, history entries=4
2025-12-07 16:39:23.500 INFO (MainThread) [custom_components.vevor_heater.coordinator] Importing 4 days of fuel history into statistics
2025-12-07 16:39:23.500 WARNING (MainThread) [custom_components.vevor_heater.coordinator] Could not import statistic for 2025-12-03: Invalid statistic_id - Statistics graph may not work
2025-12-07 16:39:23.501 WARNING (MainThread) [custom_components.vevor_heater.coordinator] Could not import statistic for 2025-12-04: Invalid statistic_id - Statistics graph may not work
2025-12-07 16:39:23.501 WARNING (MainThread) [custom_components.vevor_heater.coordinator] Could not import statistic for 2025-12-05: Invalid statistic_id - Statistics graph may not work
2025-12-07 16:39:23.501 WARNING (MainThread) [custom_components.vevor_heater.coordinator] Could not import statistic for 2025-12-06: Invalid statistic_id - Statistics graph may not work
2025-12-07 16:39:23.501 INFO (MainThread) [custom_components.vevor_heater.coordinator] Completed import of fuel history into statistics
2025-12-07 16:39:23.501 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Connecting to Vevor Heater at 3C:AB:72:7A:10:E0 (attempt 1)
2025-12-07 16:39:24.063 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Started notifications on 0000ffe1-0000-1000-8000-00805f9b34fb
2025-12-07 16:39:24.063 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Sending wake-up ping to device
2025-12-07 16:39:24.144 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📩 Received BLE data (48 bytes): da077272776c7264725c7173f56ffe6415617176166e386470617372766e8d6570197373136f726470617373776f7264
2025-12-07 16:39:24.145 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Decrypted header: 0xAA66
2025-12-07 16:39:24.145 INFO (MainThread) [custom_components.vevor_heater.coordinator] 🔍 Detected protocol: AA66 encrypted (mode=4)
2025-12-07 16:39:24.145 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Parsed AA66 encrypted: {'running_state': 1, 'error_code': 0, 'running_step': 3, 'altitude': 0.0, 'running_mode': 2, 'set_level': 2, 'set_temp': 36, 'supply_voltage': 13.0, 'case_temperature': 140, 'cab_temperature': 12.0, 'connected': False, 'hourly_fuel_consumption': None, 'daily_fuel_consumed': 1.53, 'total_fuel_consumed': 15.22, 'daily_fuel_history': {'2025-12-03': 2.26, '2025-12-04': 3.53, '2025-12-05': 4.06, '2025-12-06': 3.83}}
2025-12-07 16:39:24.145 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📋 Protocol mode changed: 0 → 4 (commands will now use AA66 encrypted format)
2025-12-07 16:39:24.564 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Wake-up ping sent
2025-12-07 16:39:24.564 INFO (MainThread) [custom_components.vevor_heater.coordinator] Successfully connected to Vevor Heater
2025-12-07 16:39:24.564 INFO (MainThread) [custom_components.vevor_heater.coordinator] 🔧 Building command packet: protocol_mode=4, cmd=1, arg=0
2025-12-07 16:39:24.565 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Using AA66 protocol header
2025-12-07 16:39:24.565 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Base packet (8 bytes): aa660c220100002f
2025-12-07 16:39:24.565 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Protocol requires encryption, encrypting packet...
2025-12-07 16:39:24.565 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Encrypted packet (48 bytes): da077f51766f724b70617373776f726470617373776f726470617373776f726470617373776f726470617373776f7264
2025-12-07 16:39:24.565 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📤 Sending command: da077f51766f724b70617373776f726470617373776f726470617373776f726470617373776f726470617373776f7264 (cmd=1, arg=0, protocol=4, len=48)
2025-12-07 16:39:24.568 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Command written to BLE characteristic
2025-12-07 16:39:29.614 WARNING (MainThread) [custom_components.vevor_heater.coordinator] ⚠️ No response received after 5.0s
2025-12-07 16:39:29.614 WARNING (MainThread) [custom_components.vevor_heater.coordinator] No status received from heater
2025-12-07 16:39:29.614 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Finished fetching vevor_heater data in 6.113 seconds (success: False)
2025-12-07 16:39:29.614 WARNING (MainThread) [custom_components.vevor_heater] Initial connection to Vevor Heater at 3C:AB:72:7A:10:E0 failed: No status received from heater. Setup will complete anyway and retry in background. Entities will show as unavailable until connection succeeds. Make sure the heater is powered on, in Bluetooth range, and the Vevor app is disconnected.
2025-12-07 16:39:59.745 INFO (MainThread) [custom_components.vevor_heater.coordinator] 🔧 Building command packet: protocol_mode=4, cmd=1, arg=0
2025-12-07 16:39:59.745 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Using AA66 protocol header
2025-12-07 16:39:59.745 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Base packet (8 bytes): aa660c220100002f
2025-12-07 16:39:59.746 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Protocol requires encryption, encrypting packet...
2025-12-07 16:39:59.746 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Encrypted packet (48 bytes): da077f51766f724b70617373776f726470617373776f726470617373776f726470617373776f726470617373776f7264
2025-12-07 16:39:59.746 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📤 Sending command: da077f51766f724b70617373776f726470617373776f726470617373776f726470617373776f726470617373776f7264 (cmd=1, arg=0, protocol=4, len=48)
2025-12-07 16:39:59.748 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Command written to BLE characteristic
2025-12-07 16:40:04.796 WARNING (MainThread) [custom_components.vevor_heater.coordinator] ⚠️ No response received after 5.0s
2025-12-07 16:40:04.796 WARNING (MainThread) [custom_components.vevor_heater.coordinator] No status received from heater
2025-12-07 16:40:04.797 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Finished fetching vevor_heater data in 5.052 seconds (success: False)

**Comment by Spettacolo83** [comment]
Hi @wifijt,

Thanks for the excellent debug logs! I found the issue - in beta.1, I was encrypting the commands to 48 bytes, but your heater expects **unencrypted commands** (it only sends encrypted responses).

I've created **v1.0.11-beta.2** to fix this:
https://github.com/Spettacolo83/homeassistant-vevor-heater/releases/tag/v1.0.11-beta.2

### What's different in beta.2:
- Commands are now sent as **8 bytes unencrypted** (not 48 bytes encrypted)
- Still uses the correct **AA66 header** (not AA55)
- The heater should now respond properly

### Expected logs:
```
🔧 Building command packet: protocol_mode=4, cmd=4, arg=20
Command packet (8 bytes, unencrypted): aa660c22041400...
📤 Sending command: aa660c22041400... (cmd=4, arg=20, protocol=4, len=8)
✅ Received response after X.Xs
🌡️ SET TEMPERATURE RESULT: requested=20°C, heater_reports=20°C, ✅ SUCCESS
```

### To test:
1. Download and extract the release
2. Replace `/config/custom_components/vevor_heater/` 
3. Restart Home Assistant completely
4. Try setting temperature to 20°C
5. Share the logs here

The key difference you should see:
- **beta.1**: `len=48` (encrypted, heater didn't respond)
- **beta.2**: `len=8` (unencrypted, heater should respond)

Let me know how it goes!

**Comment by wifijt** [comment]
nope still looks the same 
2025-12-07 17:07:25.170 DEBUG (MainThread) [custom_components.vevor_heater] Setting up Vevor Heater with address: 3C:AB:72:7A:10:E0
2025-12-07 17:07:25.188 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Loaded fuel data: total=15.22L, daily=1.53L, history entries=4
2025-12-07 17:07:25.189 INFO (MainThread) [custom_components.vevor_heater.coordinator] Importing 4 days of fuel history into statistics
2025-12-07 17:07:25.189 WARNING (MainThread) [custom_components.vevor_heater.coordinator] Could not import statistic for 2025-12-03: Invalid statistic_id - Statistics graph may not work
2025-12-07 17:07:25.189 WARNING (MainThread) [custom_components.vevor_heater.coordinator] Could not import statistic for 2025-12-04: Invalid statistic_id - Statistics graph may not work
2025-12-07 17:07:25.190 WARNING (MainThread) [custom_components.vevor_heater.coordinator] Could not import statistic for 2025-12-05: Invalid statistic_id - Statistics graph may not work
2025-12-07 17:07:25.190 WARNING (MainThread) [custom_components.vevor_heater.coordinator] Could not import statistic for 2025-12-06: Invalid statistic_id - Statistics graph may not work
2025-12-07 17:07:25.190 INFO (MainThread) [custom_components.vevor_heater.coordinator] Completed import of fuel history into statistics
2025-12-07 17:07:25.190 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Connecting to Vevor Heater at 3C:AB:72:7A:10:E0 (attempt 1)
2025-12-07 17:07:25.572 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Started notifications on 0000ffe1-0000-1000-8000-00805f9b34fb
2025-12-07 17:07:25.572 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Sending wake-up ping to device
2025-12-07 17:07:25.658 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📩 Received BLE data (48 bytes): da077272776c7264725c7273f56fe16415617176166e386470617372766e8d6570e37373136f726470617373776f7264
2025-12-07 17:07:25.659 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Decrypted header: 0xAA66
2025-12-07 17:07:25.659 INFO (MainThread) [custom_components.vevor_heater.coordinator] 🔍 Detected protocol: AA66 encrypted (mode=4)
2025-12-07 17:07:25.659 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Parsed AA66 encrypted: {'running_state': 1, 'error_code': 0, 'running_step': 3, 'altitude': 0.0, 'running_mode': 2, 'set_level': 1, 'set_temp': 36, 'supply_voltage': 13.0, 'case_temperature': 147, 'cab_temperature': 13.0, 'connected': False, 'hourly_fuel_consumption': None, 'daily_fuel_consumed': 1.53, 'total_fuel_consumed': 15.22, 'daily_fuel_history': {'2025-12-03': 2.26, '2025-12-04': 3.53, '2025-12-05': 4.06, '2025-12-06': 3.83}}
2025-12-07 17:07:25.659 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📋 Protocol mode changed: 0 → 4 (commands will now use AA66 encrypted format)
2025-12-07 17:07:26.073 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Wake-up ping sent
2025-12-07 17:07:26.073 INFO (MainThread) [custom_components.vevor_heater.coordinator] Successfully connected to Vevor Heater
2025-12-07 17:07:26.074 INFO (MainThread) [custom_components.vevor_heater.coordinator] 🔧 Building command packet: protocol_mode=4, cmd=1, arg=0
2025-12-07 17:07:26.074 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Using AA66 protocol header (mode 4)
2025-12-07 17:07:26.074 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Command packet (8 bytes, unencrypted): aa660c220100002f
2025-12-07 17:07:26.074 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📤 Sending command: aa660c220100002f (cmd=1, arg=0, protocol=4, len=8)
2025-12-07 17:07:26.077 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Command written to BLE characteristic
2025-12-07 17:07:31.126 WARNING (MainThread) [custom_components.vevor_heater.coordinator] ⚠️ No response received after 5.0s
2025-12-07 17:07:31.126 WARNING (MainThread) [custom_components.vevor_heater.coordinator] No status received from heater
2025-12-07 17:07:31.127 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Finished fetching vevor_heater data in 5.936 seconds (success: False)
2025-12-07 17:07:31.127 WARNING (MainThread) [custom_components.vevor_heater] Initial connection to Vevor Heater at 3C:AB:72:7A:10:E0 failed: No status received from heater. Setup will complete anyway and retry in background. Entities will show as unavailable until connection succeeds. Make sure the heater is powered on, in Bluetooth range, and the Vevor app is disconnected.
2025-12-07 17:08:00.831 INFO (MainThread) [custom_components.vevor_heater.coordinator] 🔧 Building command packet: protocol_mode=4, cmd=1, arg=0
2025-12-07 17:08:00.831 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Using AA66 protocol header (mode 4)
2025-12-07 17:08:00.831 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Command packet (8 bytes, unencrypted): aa660c220100002f
2025-12-07 17:08:00.831 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📤 Sending command: aa660c220100002f (cmd=1, arg=0, protocol=4, len=8)
2025-12-07 17:08:00.832 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Command written to BLE characteristic
2025-12-07 17:08:05.881 WARNING (MainThread) [custom_components.vevor_heater.coordinator] ⚠️ No response received after 5.0s
2025-12-07 17:08:05.881 WARNING (MainThread) [custom_components.vevor_heater.coordinator] No status received from heater
2025-12-07 17:08:05.881 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Finished fetching vevor_heater data in 5.051 seconds (success: False)
  Liv

**Comment by wifijt** [comment]
Actually looks like it's still sending in the aa66 format - verified that beta 2 is installed

<img width="732" height="679" alt="Image" src="https://github.com/user-attachments/assets/3fa00554-6cc4-45bd-a47e-bfff1e92013e" />

**Comment by wifijt** [comment]
Well using F is certainly confusing and something I was thinking it could be - but that's a poor design choice on vevor's part F to C should be display only.

We are really close - the set temp works (sort of) when I set the temp to 62 (16.67 °C)  it's bumping it back down to 61 - I think you are sending whole celsius values when it would need to be a float 

Here are the logs 

2025-12-07 18:25:32.712 INFO (MainThread) [custom_components.vevor_heater.coordinator] 🔧 Building command packet: protocol_mode=4, cmd=1, arg=0
2025-12-07 18:25:32.712 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Using AA55 protocol header (heater only accepts AA55 commands)
2025-12-07 18:25:32.712 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Command packet (8 bytes, AA55): aa550c220100002f
2025-12-07 18:25:32.712 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📤 Sending command: aa550c220100002f (cmd=1, arg=0, protocol=4, len=8)
2025-12-07 18:25:32.714 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Command written to BLE characteristic
2025-12-07 18:25:33.035 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📩 Received BLE data (48 bytes): da077272776c7264725d7273f56fe46415617176166e386470617372766e8d6570e37373136f726470617373776f7264
2025-12-07 18:25:33.035 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Decrypted header: 0xAA66
2025-12-07 18:25:33.035 INFO (MainThread) [custom_components.vevor_heater.coordinator] 🔍 Detected protocol: AA66 encrypted (mode=4)
2025-12-07 18:25:33.036 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] 🌡️ Raw set_temp from heater: 60 (byte 9)
2025-12-07 18:25:33.036 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] 🌡️ Converted from Fahrenheit: 60°F → 15°C
2025-12-07 18:25:33.036 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Parsed AA66 encrypted: {'running_state': 1, 'error_code': 0, 'running_step': 3, 'altitude': 0.0, 'running_mode': 2, 'set_level': 1, 'set_temp': 15, 'supply_voltage': 13.0, 'case_temperature': 150, 'cab_temperature': 13.0, 'connected': True, 'hourly_fuel_consumption': 0.16, 'daily_fuel_consumed': 1.62, 'total_fuel_consumed': 15.31, 'daily_fuel_history': {'2025-12-03': 2.26, '2025-12-04': 3.53, '2025-12-05': 4.06, '2025-12-06': 3.83}}
2025-12-07 18:25:33.095 INFO (MainThread) [custom_components.vevor_heater.climate] Setting target temperature to 16°C
2025-12-07 18:25:33.095 INFO (MainThread) [custom_components.vevor_heater.coordinator] 🌡️ SET TEMPERATURE REQUEST: target=16°C (60°F), current=15, mode=2, protocol=4 (using Fahrenheit)
2025-12-07 18:25:33.095 INFO (MainThread) [custom_components.vevor_heater.coordinator] 🔧 Building command packet: protocol_mode=4, cmd=4, arg=60
2025-12-07 18:25:33.096 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Using AA55 protocol header (heater only accepts AA55 commands)
2025-12-07 18:25:33.096 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Command packet (8 bytes, AA55): aa550c22043c006e
2025-12-07 18:25:33.096 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📤 Sending command: aa550c22043c006e (cmd=4, arg=60, protocol=4, len=8)
2025-12-07 18:25:33.097 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Command written to BLE characteristic
2025-12-07 18:25:33.581 INFO (MainThread) [custom_components.vevor_heater.coordinator] 📩 Received BLE data (48 bytes): da077772776c7264725d7273f56fe46415617176166e386470617372766e8d6570e37373136f726470617373776f7264
2025-12-07 18:25:33.582 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Decrypted header: 0xAA66
2025-12-07 18:25:33.582 INFO (MainThread) [custom_components.vevor_heater.coordinator] 🔍 Detected protocol: AA66 encrypted (mode=4)
2025-12-07 18:25:33.582 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] 🌡️ Raw set_temp from heater: 60 (byte 9)
2025-12-07 18:25:33.582 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] 🌡️ Converted from Fahrenheit: 60°F → 15°C
2025-12-07 18:25:33.582 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Parsed AA66 encrypted: {'running_state': 1, 'error_code': 0, 'running_step': 3, 'altitude': 0.0, 'running_mode': 2, 'set_level': 1, 'set_temp': 15, 'supply_voltage': 13.0, 'case_temperature': 150, 'cab_temperature': 13.0, 'connected': True, 'hourly_fuel_consumption': 0.16, 'daily_fuel_consumed': 1.62, 'total_fuel_consumed': 15.31, 'daily_fuel_history': {'2025-12-03': 2.26, '2025-12-04': 3.53, '2025-12-05': 4.06, '2025-12-06': 3.83}}
2025-12-07 18:25:33.602 INFO (MainThread) [custom_components.vevor_heater.coordinator] ✅ Received response after 0.4s (protocol=4)
2025-12-07 18:25:33.602 INFO (MainThread) [custom_components.vevor_heater.coordinator] 🌡️ SET TEMPERATURE RESULT: requested=16°C, heater_reports=15°C, ❌ FAILED - heater did not accept
2025-12-07 18:25:33.623 INFO (MainThread) [custom_components.vevor_heater.coordinator] ✅ Received response after 0.8s (protocol=4)
2025-12-07 18:25:33.623 DEBUG (MainThread) [custom_components.vevor_heater.coordinator] Finished fetching vevor_heater data in 0.912 seconds (success: True)
